[workspace]
authors = ["Daniel Morcuende <daniel.morcuende@cta-observatory.org>"]
channels = ["conda-forge"]
name = "5_Timing_analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
gammapy = "2.0.*"
ipywidgets = ">=8.1.8,<9"
astroquery = ">=0.4.11,<0.5"
tqdm = ">=4.67.1,<5"
ipykernel = ">=7.1.0,<8"
jupyterlab = ">=4.4.10,<5"
gdown = ">=5.2.0,<6"
