[workspace]
authors = ["Daniel Morcuende <daniel.morcuende@cta-observatory.org>"]
channels = ["conda-forge"]
name = "7. Multi-instrument"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
gammapy = "2.0.*"
jupyterlab = ">=4.4.10,<5"
ipykernel = ">=7.1.0,<8"
ipywidgets = ">=8.1.8,<9"
